
-- create tables and indexes
\i alignment_scores.sql
\i benchmark.sql
\i cath_domain.sql
\i cathedral_result.sql
\i cath_grams.sql
\i cath_hashes.sql
\i cath_name.sql
\i chain_grams.sql
\i chain_hashes.sql
\i chain.sql
\i ecod_domain.sql
\i ecod_grams.sql
\i ecod_hashes.sql
\i mtm_result.sql
\i residue.sql
\i response_time.sql
\i rupee_result.sql
\i scop_domain.sql
\i scop_grams.sql
\i scop_hashes.sql
\i scop_name.sql
\i ssm_result.sql
\i upload_grams.sql
\i upload_hashes.sql

-- create functions
\i get_alignment_scores.sql
\i get_cath_augmented_results.sql
\i get_cath_band_matches.sql
\i get_cathedral_results.sql
\i get_cath_grams_split.sql
\i get_cath_grams.sql
\i get_cath_hashes.sql
\i get_cath_split_matches.sql
\i get_cath_split.sql
\i get_chain_augmented_results.sql
\i get_chain_band_matches.sql
\i get_chain_grams_split.sql
\i get_chain_grams.sql
\i get_chain_hashes.sql
\i get_chain_split_matches.sql
\i get_chain_split.sql
\i get_ecod_augmented_results.sql
\i get_ecod_band_matches.sql
\i get_ecod_grams_split.sql
\i get_ecod_grams.sql
\i get_ecod_hashes.sql
\i get_ecod_split_matches.sql
\i get_ecod_split.sql
\i get_mtm_results.sql
\i get_probabilities.sql
\i get_rupee_results.sql
\i get_scop_augmented_results.sql
\i get_scop_band_matches.sql
\i get_scop_grams_split.sql
\i get_scop_grams.sql
\i get_scop_hashes.sql
\i get_scop_split_matches.sql
\i get_scop_split.sql
\i get_ssm_results.sql
\i get_upload_grams.sql
\i get_upload_hashes.sql
\i insert_alignment_scores.sql
\i insert_cath_grams.sql
\i insert_cath_hashes.sql
\i insert_chain_grams.sql
\i insert_chain_hashes.sql
\i insert_ecod_grams.sql
\i insert_ecod_hashes.sql
\i insert_scop_grams.sql
\i insert_scop_hashes.sql
\i insert_upload_grams.sql
\i insert_upload_hashes.sql

